namespace NexHire.Application.Matching;

/// <summary>
/// Contains the matching information required
/// to compare one candidate application.
///
/// This internal model keeps comparison logic
/// independent from API DTOs and database entities.
/// </summary>
public class CandidateComparisonInput
{
    /// <summary>
    /// Unique job application identifier.
    /// </summary>
    public Guid ApplicationId { get; set; }

    /// <summary>
    /// Candidate's job seeker profile identifier.
    /// </summary>
    public Guid JobSeekerProfileId { get; set; }

    /// <summary>
    /// Candidate's final weighted matching score.
    /// </summary>
    public decimal TotalScore { get; set; }

    /// <summary>
    /// Indicates whether the candidate passed
    /// mandatory eligibility requirements.
    /// </summary>
    public bool IsEligible { get; set; }

    /// <summary>
    /// Recommendation generated by the
    /// recommendation engine.
    /// </summary>
    public string Recommendation { get; set; } = string.Empty;

    /// <summary>
    /// Detailed weighted category scores used
    /// for side-by-side candidate comparison.
    /// </summary>
    public List<WeightedCategoryScoreResult> ScoreDetails { get; set; } = new();
}