namespace NexHire.Application.Matching;

/// <summary>
/// Represents one candidate in a side-by-side
/// candidate comparison result.
///
/// This internal result is later mapped to the
/// CandidateComparisonDto returned by the API.
/// </summary>
public class CandidateComparisonResult
{
    /// <summary>
    /// Unique job application identifier.
    /// </summary>
    public Guid ApplicationId { get; set; }

    /// <summary>
    /// Candidate's job seeker profile identifier.
    /// </summary>
    public Guid JobSeekerProfileId { get; set; }

    /// <summary>
    /// Final weighted matching score.
    /// </summary>
    public decimal TotalScore { get; set; }

    /// <summary>
    /// Indicates whether the candidate passed
    /// mandatory eligibility requirements.
    /// </summary>
    public bool IsEligible { get; set; }

    /// <summary>
    /// Recommendation generated by the
    /// recommendation engine.
    /// </summary>
    public string Recommendation { get; set; } = string.Empty;

    /// <summary>
    /// Detailed category-level weighted scores
    /// used for side-by-side comparison.
    /// </summary>
    public List<WeightedCategoryScoreResult> ScoreDetails { get; set; } = new();
}