namespace NexHire.Application.Matching;

/// <summary>
/// Represents the final weighted result of one
/// matching score category.
///
/// Example:
/// Raw Score = 80
/// Weight = 30
/// Weighted Points = 24
/// Maximum Weighted Points = 30
/// </summary>
public class WeightedCategoryScoreResult
{
    /// <summary>
    /// Matching category name such as Skills,
    /// Experience or Education.
    /// </summary>
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Score produced by the individual category
    /// calculator before applying its weight.
    /// Range: 0 to 100.
    /// </summary>
    public decimal RawScore { get; set; }

    /// <summary>
    /// Configured category weight.
    /// </summary>
    public decimal Weight { get; set; }

    /// <summary>
    /// Points contributed by this category
    /// to the final overall score.
    /// </summary>
    public decimal WeightedPoints { get; set; }

    /// <summary>
    /// Maximum points this category can contribute.
    /// Normally equal to its configured weight.
    /// </summary>
    public decimal MaximumWeightedPoints { get; set; }

    /// <summary>
    /// Human-readable category status.
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>
    /// Explanation generated by the category calculator.
    /// </summary>
    public string Explanation { get; set; } = string.Empty;
}