using NexHire.Application.DTOs.Auth;using NexHire.Application.Interfaces.Repositories;using NexHire.Application.Interfaces.Services;using NexHire.Application.Validators;using NexHire.Domain.Entities;using NexHire.Domain.Enums;
namespace NexHire.Application.Services;
public sealed class AuthService(IUserRepository users, IPasswordHasher passwords, ITokenService tokens) : IAuthService
{
    public async Task<LoginResponseDto> RegisterAsync(RegisterRequestDto dto,CancellationToken ct=default){var validation=await new RegisterRequestValidator().ValidateAsync(dto,ct);if(!validation.IsValid)throw new ArgumentException(string.Join(" ",validation.Errors.Select(x=>x.ErrorMessage)));var email=dto.Email.Trim().ToUpperInvariant();if(await users.EmailExistsAsync(email,ct))throw new InvalidOperationException("Email is already registered.");var user=new User{FirstName=dto.FirstName.Trim(),LastName=dto.LastName.Trim(),PhoneNumber=dto.PhoneNumber?.Trim(),Email=dto.Email.Trim().ToLowerInvariant(),NormalizedEmail=email,Role=Enum.Parse<UserRole>(dto.Role,true)};user.PasswordHash=passwords.Hash(dto.Password);await users.AddUserAsync(user,ct);return await IssueTokensAsync(user,ct);}
    public async Task<LoginResponseDto?> LoginAsync(LoginRequestDto dto,CancellationToken ct=default){var user=await users.GetByEmailAsync(dto.Email.Trim().ToUpperInvariant(),ct);if(user is null||user.Status!=UserStatus.Active||!passwords.Verify(dto.Password,user.PasswordHash))return null;return await IssueTokensAsync(user,ct);}
    public async Task<LoginResponseDto?> RefreshAsync(string raw,CancellationToken ct=default){var old=await users.GetRefreshTokenAsync(tokens.HashToken(raw),ct);if(old is null||!old.IsValid||old.User.Status!=UserStatus.Active)return null;old.RevokedAtUtc=DateTime.UtcNow;return await IssueTokensAsync(old.User,ct);}
    public async Task<string?> ForgotPasswordAsync(string email,CancellationToken ct=default){var user=await users.GetByEmailAsync(email.Trim().ToUpperInvariant(),ct);if(user is null)return null;var raw=tokens.CreateSecureToken();user.PasswordResetTokenHash=tokens.HashToken(raw);user.PasswordResetExpiresAtUtc=DateTime.UtcNow.AddMinutes(30);await users.SaveChangesAsync(ct);return raw;}
    public async Task<bool> ResetPasswordAsync(ResetPasswordRequestDto dto,CancellationToken ct=default){if(!PasswordPolicy.IsStrong(dto.NewPassword)||dto.NewPassword!=dto.ConfirmNewPassword)return false;var user=await users.GetByResetTokenHashAsync(tokens.HashToken(dto.Token),ct);if(user is null||user.PasswordResetExpiresAtUtc<=DateTime.UtcNow)return false;user.PasswordHash=passwords.Hash(dto.NewPassword);user.PasswordResetTokenHash=null;user.PasswordResetExpiresAtUtc=null;RevokeAll(user);await users.SaveChangesAsync(ct);return true;}
    public async Task<bool> ChangePasswordAsync(Guid id,ChangePasswordRequestDto dto,CancellationToken ct=default){if(!PasswordPolicy.IsStrong(dto.NewPassword)||dto.NewPassword!=dto.ConfirmNewPassword||dto.CurrentPassword==dto.NewPassword)return false;var user=await users.GetByIdAsync(id,ct);if(user is null||!passwords.Verify(dto.CurrentPassword,user.PasswordHash))return false;user.PasswordHash=passwords.Hash(dto.NewPassword);RevokeAll(user);await users.SaveChangesAsync(ct);return true;}
    public async Task<bool> LogoutAsync(string raw,CancellationToken ct=default){var token=await users.GetRefreshTokenAsync(tokens.HashToken(raw),ct);if(token is null||token.RevokedAtUtc is not null)return false;token.RevokedAtUtc=DateTime.UtcNow;await users.SaveChangesAsync(ct);return true;}
    public async Task<CurrentUserResponseDto?> GetCurrentUserAsync(Guid id,CancellationToken ct=default){var u=await users.GetByIdAsync(id,ct);return u is null?null:new(u.Id,u.Email,u.FullName,u.Role.ToString(),u.Status.ToString());}
    private async Task<LoginResponseDto> IssueTokensAsync(User user,CancellationToken ct){var(access,expires)=tokens.CreateAccessToken(user);var raw=tokens.CreateSecureToken();await users.AddRefreshTokenAsync(new RefreshToken{UserId=user.Id,TokenHash=tokens.HashToken(raw),ExpiresAtUtc=DateTime.UtcNow.AddDays(7)},ct);await users.SaveChangesAsync(ct);return new(access,raw,expires,user.Role.ToString(),user.FullName);}
    private static void RevokeAll(User user){foreach(var t in user.RefreshTokens.Where(x=>x.RevokedAtUtc is null))t.RevokedAtUtc=DateTime.UtcNow;}
}
